file_format: "1"
id: ed48fcorne
name: EDF48 Corne
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - ed48fcorne_left
  - ed48fcorne_right
